/* Served only after authenticated private-license verification. */
window.RPG=(()=>{
 'use strict';
 let current=null,installed=false,pickerGeneration=0,creatingId=null,restoreBusy=false;
 const names={system:'Qual sistema e edição vamos jogar?',role:'Você vai jogar como mestre ou jogador?',setting:'Qual cenário e estilo de RPG?',tone:'Qual o tom e a intensidade da violência ficcional?',rules:'Quais regras da casa e fontes devemos seguir?',characters:'Quem são os personagens e quais os fatos iniciais?',objections:'Existe alguma objeção, limite ou tema a evitar?',dice:'Como vamos fazer as rolagens?',style:'Que estilo de narração você prefere?'};
 const eventNames={setup:'Regras da mesa',session:'Sessão confirmada',user:'Ação ou pedido',narrator:'Narração concluída',canon:'Fato confirmado',note:'Anotação',roll:'Rolagem de dados',archive:'Estado da campanha',interrupted:'Rascunho interrompido',cancelled:'Tentativa cancelada',restored:'Backup restaurado'};
 const limits={system:180,setting:2000,tone:1000,rules:7000,characters:7000,objections:3000,style:2000};
 const examples={system:'Ex.: Tormenta20, D&D 5e (edição), sistema próprio…',setting:'Fantasia sombria, investigação, terror, ficção científica…',tone:'Ex.: terror intenso com combates e mortes; descreva o tom desejado.',rules:'Informe regras oficiais/da casa. Se não houver, escreva “sem regras da casa”.',characters:'Nomes, fichas, objetivos e o que já aconteceu. Não vamos presumir fatos.',objections:'Diga o que prefere evitar. Se não houver objeções, escreva “nenhuma”.',style:'Primeira ou terceira pessoa? Texto curto ou detalhado? Mais escolhas ou narrativa livre?'};
 Object.assign(paths,{book:'M12 5C8 2 4 3 2 4v16c4-2 7-1 10 1m0-16c4-3 8-2 10-1v16c-4-2-7-1-10 1V5',dice:'m12 2 10 6v9l-10 5-10-5V8l10-6Zm0 0v11m10-5-10 5-10-5m10 5v9'});
 function handles(id){return id==='narrator'&&!!state.kelly?.privateLicense?.active;}
 async function authorizedFetch(url,opt={}){const {data:{session}}=await sbClient.auth.getSession();if(!session)throw Error('Entre novamente.');const r=await fetch(url,{...opt,headers:{Authorization:'Bearer '+session.access_token,...opt.headers}});if(!r.ok){const d=await r.json().catch(()=>({}));throw Object.assign(Error(d.error||'Operação indisponível.'),{status:r.status,code:d.code});}return r;}
 function base(){return '/api/kelly/rpg/campaigns/'+current.campaign.id;}
 async function refresh(){if(!current)return;const d=await api(base());attach(d);return d;}
 function closePanel(){document.querySelectorAll('.rpgModal').forEach(n=>n.remove());}
 function modal(title,subtitle){
  closePanel();const outer=el('section','modalScreen show rpgModal');outer.setAttribute('role','dialog');outer.setAttribute('aria-modal','true');outer.setAttribute('aria-label',title);
  const card=el('div','rpgDialog'),head=el('div','rpgDialogHead'),text=el('div');text.append(el('span','rpgEyebrow','SEU ESPAÇO DE CAMPANHA'),el('h2','',title));if(subtitle)text.append(el('p','',subtitle));head.append(text,action('','close',closePanel,'iconBtn'));head.lastChild.setAttribute('aria-label','Fechar');const body=el('div','rpgDialogBody');card.append(head,body);outer.append(card);document.body.append(outer);outer.addEventListener('click',e=>{if(e.target===outer)closePanel();});setTimeout(()=>head.querySelector('button').focus(),0);return body;
 }
 function status(box,text){let n=box.querySelector('.rpgFeedback');if(!n){n=el('p','rpgFeedback');n.setAttribute('role','status');box.append(n);}n.textContent=text;return n;}
 async function install(){
  if(installed)return;
  const css=await(await authorizedFetch('/api/kelly/rpg/style')).text();const style=el('style');style.id='rpgStyle';style.textContent=css;document.head.append(style);
  const btn=action('Campanhas','book',()=>openStart(),'menuRow');btn.id='rpgCampaignsBtn';$('#drawerBottom')?.append(btn);$('.drawerBottom').insertBefore(btn,$('#licenseBtn'));
  const bar=el('div','rpgBar hidden');bar.id='rpgBar';$('.topbar').after(bar);installed=true;
 }
 function clear(){current=null;state.rpgCurrent=null;state.rpgBefore=null;creatingId=null;$('#rpgBar')?.classList.add('hidden');}
 function destroy(){closePanel();clear();installed=false;$('#rpgStyle')?.remove();$('#rpgCampaignsBtn')?.remove();$('#rpgBar')?.remove();}
 function attach(d){current=d;state.rpgCurrent=d;const bar=$('#rpgBar');if(!bar)return;bar.replaceChildren();bar.classList.toggle('hidden',!d);if(!d)return;
  const label=el('div','rpgCampaignLabel',d.campaign.title);label.append(el('small','',`${d.campaign.head} registros · ${d.campaign.setup.system}`));bar.append(label,action('Diário','book',()=>openJournal()),action('Dados','dice',()=>openDice()));
  if(d.pending){const warning=action(d.pending.status==='failed'?'Retomar ação pendente':'Conferir ação pendente','down',()=>openPending(),'rpgPendingBadge');bar.append(warning);}
 }
 async function choose(){if(state.busy)return;setMode('narrator',false);if(current){input.focus();return;}await createChat();}
 function welcome(){messages.replaceChildren();state.currentMessages=[];$('#chatHeading').textContent='Preparação da mesa';const box=el('div','welcome rpgWelcome');box.innerHTML=`<div class="welcomeLabel">${icon('book')} A HISTÓRIA COMEÇA COM UM ACORDO</div><h1>Sua mesa.<br><span>Um mundo de caminhos.</span></h1><p>Antes da primeira cena, vamos combinar o sistema,<br>as regras, o estilo e os limites da campanha.</p><div class="rpgWelcomeActions"></div>`;box.querySelector('.rpgWelcomeActions').append(action('Preparar ou retomar uma campanha','book',()=>openStart(),'rpgPrimary'));messages.append(box);$('#exportChatBtn').disabled=true;}
 async function openStart(){
  if(state.busy)return toast('Interrompa a narração antes de mudar de campanha.');closeDrawer();closeModeMenu();const body=modal('Antes da primeira cena','Qual história vamos jogar? Toda campanha começa com suas regras e objeções confirmadas.');
  body.append(action('Preparar uma nova mesa','plus',()=>setupForm(),'rpgPrimary'));
  const restore=el('input');restore.type='file';restore.accept='.ndjson,.jsonl';restore.hidden=true;body.append(action('Restaurar um backup','upload',()=>restore.click(),'smallBtn'),restore);restore.onchange=()=>restore.files[0]&&importCampaign(restore.files[0]);
  const list=el('div','rpgCampaignList');list.append(el('h3','','Suas campanhas'));body.append(list);const generation=++pickerGeneration;
  try{let cursor;do{const d=await api('/api/kelly/rpg/campaigns'+(cursor?'?before='+encodeURIComponent(cursor):''));if(generation!==pickerGeneration||!body.isConnected)return;for(const c of d.campaigns){const b=el('button','rpgCampaignCard');b.type='button';b.append(el('strong','',c.title),el('small','',`${c.setup.system} · ${c.head} registros · ${c.status==='archived'?'arquivada':c.status==='restoring'?'restauração incompleta':'em andamento'}`));b.onclick=()=>c.status==='restoring'?toast('Selecione o mesmo arquivo de backup para retomar a restauração.'):reviewCampaign(c.id);list.append(b);}cursor=d.next;}while(cursor);if(list.children.length===1)list.append(el('p','settingsHelp','Sua primeira campanha aparecerá aqui.'));}catch(e){status(body,e.message);}
 }
 function setupForm(existing=null){
  const body=modal(existing?'Revisar regras da mesa':'Vamos preparar sua mesa','Responda às perguntas. A narração só começa depois da sua confirmação.');const form=el('form','rpgSetupForm');body.append(form);
  const titleLabel=el('label','','Como vamos chamar a campanha?'),title=el('input');title.name='title';title.maxLength=100;title.required=true;title.value=existing?.title||'';title.placeholder='Ex.: Os sinos de Eldória';titleLabel.append(title);form.append(titleLabel);
  for(const [key,label] of Object.entries(names)){const wrap=el('label','',label);let field;
   if(key==='role'||key==='dice'){field=el('select');const options=key==='role'?[['','Selecione…'],['mestre','Eu sou o mestre · assistência à mesa'],['jogador','Eu sou jogador · narração do mundo']]:[['','Selecione…'],['usuario','Eu informo os resultados dos dados'],['rolador','Usarei o rolador registrado da interface']];for(const [value,text]of options){const option=el('option','',text);option.value=value;field.append(option);}}
   else{field=el(key==='system'?'input':'textarea');field.maxLength=limits[key];if(field.tagName==='TEXTAREA')field.rows=key==='characters'||key==='rules'?3:2;field.placeholder=examples[key];}
   field.name=key;field.required=true;field.value=existing?.setup?.[key]||'';wrap.append(field);form.append(wrap);
  }
  const confirmLabel=el('label','rpgCheck'),confirm=el('input');confirm.type='checkbox';confirm.required=true;confirmLabel.append(confirm,document.createTextNode('Revisei as respostas, incluindo minhas objeções, e confirmo a preparação da mesa.'));form.append(confirmLabel);
  const submit=el('button','rpgPrimary',existing?'Salvar revisão das regras':'Confirmar e abrir a mesa');submit.type='submit';form.append(submit);
  form.onsubmit=async e=>{e.preventDefault();submit.disabled=true;try{const setup={};for(const key of Object.keys(names))setup[key]=form.elements[key].value;let c;
   if(existing){c=(await api('/api/kelly/rpg/campaigns/'+existing.id+'/setup',{method:'POST',body:JSON.stringify({title:title.value,setup,confirmed:true,revision:existing.head})})).campaign;await refresh();closePanel();toast('Revisão registrada no diário.');return;}
   creatingId ||= crypto.randomUUID();c=(await api('/api/kelly/rpg/campaigns',{method:'POST',body:JSON.stringify({id:creatingId,title:title.value,setup,confirmed:true})})).campaign;creatingId=null;await connect(c,setup.objections);closePanel();
  }catch(err){status(body,err.message);}finally{submit.disabled=false;}};
 }
 async function reviewCampaign(id){
  try{const d=await api('/api/kelly/rpg/campaigns/'+id);const c=d.campaign;if(d.pending){attach(d);setMode('narrator',false);return openPending();}
   const body=modal('Revisar antes de retomar',c.title+' · '+c.head+' registros preservados');const dl=el('dl','rpgSetupReview');for(const key of Object.keys(names)){dl.append(el('dt','',names[key]),el('dd','',c.setup[key]));}body.append(dl);
   const form=el('form'),label=el('label','','Quais objeções e limites devem valer a partir desta sessão?'),field=el('textarea');field.required=true;field.rows=2;field.maxLength=3000;field.value=c.setup.objections;field.placeholder='Inclua os limites anteriores que continuam valendo e qualquer nova objeção.';label.append(field);form.append(label);
   const checkLabel=el('label','rpgCheck'),check=el('input');check.type='checkbox';check.required=true;checkLabel.append(check,document.createTextNode('Revisei as regras e confirmo a continuação desta campanha.'));const btn=el('button','rpgPrimary','Confirmar e retomar');btn.type='submit';form.append(checkLabel,btn);body.append(form);
   form.onsubmit=async e=>{e.preventDefault();btn.disabled=true;try{await connect(c,field.value);closePanel();}catch(err){status(body,err.message);}finally{btn.disabled=false;}};
  }catch(e){toast(e.message);}
 }
 async function connect(c,objections){
  const d=await api('/api/chats',{method:'POST'});await api('/api/kelly/rpg/campaigns/'+c.id+'/connect',{method:'POST',body:JSON.stringify({chatId:d.chat.id,revision:c.head,confirmed:true,objections})});state.chats.unshift(d.chat);setMode('narrator',false);await openChat(d.chat.id);
  if(!state.currentMessages.length){messages.replaceChildren();const row=addMessage('Mesa preparada. As regras e objeções foram registradas. Quando estiver pronto, descreva sua primeira ação ou peça para abrir a cena.','assistant');row.classList.add('rpgSetupNotice');}
 }
 function decorate(){if(!current)return;for(const row of messages.querySelectorAll('.msgRow')){if(row.querySelector('.rpgSource'))continue;const index=[...messages.querySelectorAll('.msgRow')].indexOf(row),m=state.currentMessages[index];if(m?.rpgSeq)row.prepend(action('E'+m.rpgSeq,'book',()=>openJournal('E'+m.rpgSeq),'textBtn rpgSource'));}}
 async function openPending(){
  try{await refresh();if(!current.pending)return toast('Não há ação pendente.');const p=current.pending,body=modal('Uma ação precisa de confirmação','O pedido original e o rascunho estão preservados. Um rascunho não define o que aconteceu na história.');
   body.append(el('h3','','Ação do jogador'),el('p','rpgPlain',unpack(p.content).text||'Mensagem com anexos.'),el('h3','','Rascunho não confirmado'),el('pre','rpgDraft',p.draft||'Nenhum trecho recebido ainda.'));
   body.append(action('Retomar a mesma ação','up',async()=>{try{await refresh();const latest=current.pending;if(!latest)return toast('A ação já foi concluída. Reabra a conversa.');if(latest.status==='pending'&&Date.parse(latest.lease_until)>Date.now())return toast('A tentativa ainda está ativa. Aguarde ou cancele.');
     const actual=state.chatId?await api('/api/chats/'+state.chatId).catch(()=>null):null;if(actual?.rpg?.campaign.id!==current.campaign.id){const links=await api('/api/chats');let linked=null;for(const chat of links.chats){try{const view=await api('/api/chats/'+chat.id);if(view.rpg?.campaign.id===current.campaign.id){linked=chat.id;break;}}catch{}}if(!linked)return toast('Cancele a tentativa para abrir uma nova sessão; o pedido e rascunho ficarão no diário.');await openChat(linked);}
     const decoded=unpack(latest.content);input.value=decoded.text;state.attachments=decoded.attachments;drawAttachments();closePanel();await send(latest);
   }catch(e){status(body,e.message);}},'rpgPrimary'));
   body.append(action('Cancelar tentativa e preservar o registro','close',async()=>{try{await api(base()+'/cancel',{method:'POST',body:JSON.stringify({requestId:p.request_id,reason:'Tentativa cancelada explicitamente pelo usuário.'})});await refresh();closePanel();toast('Tentativa cancelada. O registro foi preservado.');}catch(e){status(body,e.message);}},'smallBtn'));
  }catch(e){toast(e.message);}
 }
 async function send(retry=null){
  if(state.busy||state.reading)return;if(!current||!state.chatId)return openStart();if(!handles(state.mode))return;
  if(current.pending&&!retry)return openPending();const text=input.value.trim(),attachments=[...state.attachments];if(!text&&!attachments.length)return;
  const requestId=retry?.request_id||crypto.randomUUID(),chatId=state.chatId,user=state.me.user.id;let live,done=false;
  setBusy(true);state.controller=new AbortController();
  try{
   if(messages.querySelector('.welcome,.rpgSetupNotice'))messages.replaceChildren();if(!retry)addMessage(attachments.length?JSON.stringify({_zulu:5,text,attachments}):text,'user');input.value='';clearAttachments();resize();live=liveMessage();live.row.classList.add('rpgProvisional');scrollToEnd(true);
   const response=await authorizedFetch('/api/chats/'+chatId+'/message',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,attachments,stream:true,mode:'narrator',requestId,revision:current.campaign.head}),signal:state.controller.signal});
   await readNDJSON(response,event=>{if(event.type==='delta')live.delta(event.text);if(event.type==='memory')$('#status').textContent='Diário consultado';if(event.type==='error')throw Error(event.error);if(event.type==='done'){done=true;live.row.classList.remove('rpgProvisional');live.finish(event.reply);current.campaign.head=event.rpg.head;current.pending=null;attach(current);}});
   if(!done)throw Error('A conexão terminou antes da confirmação. Confira a ação pendente no diário.');
  }catch(e){if(state.me?.user?.id!==user)return;live?.finish(live.raw||'',e.name==='AbortError'?'Interrompido. A ação está no diário; confira a tentativa pendente.':e.message,true);if(!done){input.value=text;state.attachments=attachments;drawAttachments();resize();}toast(e.name==='AbortError'?'Confira a ação pendente antes de continuar.':e.message);}
  finally{live?.dispose();setBusy(false);state.controller=null;if(state.me?.user?.id===user){await refresh().catch(e=>toast(e.message));if(done&&state.chatId===chatId)await openChat(chatId);}}
 }
 async function openJournal(query=''){
  if(!current)return openStart();if(state.busy)return toast('Aguarde ou interrompa a narração antes de abrir o diário.');await refresh().catch(e=>toast(e.message));const body=modal('Diário da campanha',current.campaign.title+' · registros com fontes e correções preservadas');
  const actions=el('div','rpgActions');actions.append(action('Confirmar um fato','plus',()=>factForm()),action('Anotar','write',()=>noteForm()),action('Regras da mesa','settings',()=>setupForm(current.campaign)),action('Backup completo','download',()=>exportCampaign()),action(current.campaign.status==='archived'?'Reativar':'Arquivar','book',async()=>{try{await api(base()+'/archive',{method:'POST',body:JSON.stringify({archived:current.campaign.status!=='archived',revision:current.campaign.head})});await refresh();closePanel();toast('Estado atualizado; diário preservado.');}catch(e){status(body,e.message);}}));body.append(actions);
  if(current.pending)body.append(action('Conferir ação pendente','down',()=>openPending(),'rpgPrimary'));
  const facts=el('div','rpgFacts');facts.append(el('h3','','Fatos confirmados'));function appendFacts(items){for(const fact of items){const b=el('button','rpgFact');b.append(el('strong','',fact.key),el('span','',fact.value),el('small','',`${fact.pinned?'Fixado no contexto':'Guardado no diário'} · E${fact.source_seq}`));b.onclick=()=>factForm(fact);facts.append(b);}}appendFacts(current.facts);let factCursor=current.factsNext;if(factCursor){const more=action('Carregar mais fatos','down',async()=>{more.disabled=true;try{const d=await api(base()+'/facts?after='+encodeURIComponent(factCursor));more.remove();appendFacts(d.facts);factCursor=d.factsNext;if(factCursor)facts.append(more);}catch(e){status(body,e.message);}finally{more.disabled=false;}},'textBtn');facts.append(more);}if(!current.facts.length)facts.append(el('p','settingsHelp','Fixe aqui personagens, inventário, regras e consequências essenciais. Só você confirma esses fatos.'));body.append(facts);
  const form=el('form','rpgSearch'),search=el('input');search.placeholder='Buscar nomes, escolhas, palavras ou E123';search.value=query;search.setAttribute('aria-label','Buscar no diário');const b=el('button','smallBtn','Buscar');form.append(search,b);body.append(form);const list=el('div','rpgEvents');body.append(list);
  async function load(before){try{if(!before)list.replaceChildren();const params=new URLSearchParams();if(search.value.trim())params.set('q',search.value.trim());else if(before)params.set('before',before);const d=await api(base()+'/journal?'+params);list.querySelector('.rpgOlder')?.remove();for(const event of d.events){const card=el('article','rpgEvent'),head=el('div','rpgEventHead',`E${event.seq} · ${eventNames[event.kind]||event.kind} · ${new Date(event.created_at).toLocaleString('pt-BR')}`),text=el('div','rpgPlain',unpack(event.content).text);card.append(head,text);if(unpack(event.content).attachments.length)card.append(el('small','','Inclui anexos, preservados no backup completo.'));card.append(action('Copiar referência','copy',()=>copyText('[E'+event.seq+']')),action('Usar como fonte','plus',()=>factForm(null,event.seq)));list.append(card);}if(d.next){const older=action('Carregar registros anteriores','up',()=>load(d.next),'textBtn rpgOlder');list.append(older);}if(!d.events.length)list.append(el('p','settingsHelp','Nenhum registro encontrado. Tente outro termo ou a referência exata.'));}catch(e){status(body,e.message);}}
  form.onsubmit=e=>{e.preventDefault();load();};await load();
 }
 function factForm(existing=null,source=null){const body=modal(existing?'Revisar fato confirmado':'Confirmar um fato','Mudanças criam um novo registro; o histórico original permanece no diário.');const form=el('form','rpgSetupForm');body.append(form);
  const controls={};for(const [key,label,tag,max]of [['key','Nome do fato','input',100],['value','O que é confirmado nesta campanha?','textarea',4000],['sources','Fontes (números de eventos separados por vírgula)','input',200]]){const wrap=el('label','',label),field=el(tag);field.name=key;field.maxLength=max;field.required=key!=='sources';field.value=key==='sources'?(source?String(source):existing?.source_seq?String(existing.source_seq):''):existing?.[key]||'';if(tag==='textarea')field.rows=5;wrap.append(field);form.append(wrap);controls[key]=field;}
  const category=el('select');category.setAttribute('aria-label','Categoria do fato');for(const name of ['personagem','inventario','missao','regra','progresso']){const o=el('option','',name);o.value=name;category.append(o);}category.value=existing?.category||'progresso';form.append(category);
  const wrap=el('label','rpgCheck'),pin=el('input');pin.type='checkbox';pin.checked=existing?.pinned??true;wrap.append(pin,document.createTextNode('Manter este fato sempre no contexto da campanha'));form.append(wrap,el('p','settingsHelp','Sem fonte, o fato será registrado como declaração sua. Desafixar mantém o registro pesquisável.'));
  const submit=el('button','rpgPrimary','Confirmar fato');submit.type='submit';form.append(submit);form.onsubmit=async e=>{e.preventDefault();submit.disabled=true;try{const sources=controls.sources.value.split(',').map(v=>v.trim()).filter(Boolean).map(Number);await api(base()+'/canon',{method:'POST',body:JSON.stringify({key:controls.key.value,value:controls.value.value,sources,category:category.value,pinned:pin.checked,revision:current.campaign.head})});await refresh();await openJournal();}catch(err){status(body,err.message);}finally{submit.disabled=false;}};
 }
 function noteForm(){const body=modal('Anotação do mestre ou jogador','Registre decisões da mesa ou detalhes importantes sem pedir uma narração.');const form=el('form'),text=el('textarea');text.rows=7;text.maxLength=12000;text.required=true;text.setAttribute('aria-label','Anotação');const b=el('button','rpgPrimary','Guardar no diário');b.type='submit';form.append(text,b);body.append(form);form.onsubmit=async e=>{e.preventDefault();b.disabled=true;try{await api(base()+'/note',{method:'POST',body:JSON.stringify({text:text.value,revision:current.campaign.head})});await refresh();await openJournal();}catch(err){status(body,err.message);}finally{b.disabled=false;}};}
 function openDice(){if(!current)return openStart();if(state.busy)return toast('Aguarde a narração terminar.');const body=modal('Dados registrados','A rolagem será guardada no diário. Combine primeiro o teste e suas consequências.');const form=el('form'),field=el('input');field.placeholder='Ex.: 1d20+3';field.value='1d20';field.required=true;field.setAttribute('aria-label','Expressão dos dados');const btn=el('button','rpgPrimary','Rolar e registrar');btn.type='submit';form.append(field,btn);body.append(form);let requestId=crypto.randomUUID();form.onsubmit=async e=>{e.preventDefault();btn.disabled=true;try{const d=await api(base()+'/roll',{method:'POST',body:JSON.stringify({expression:field.value,revision:current.campaign.head,requestId})});status(body,d.event.content+' [E'+d.event.seq+']');await refresh();requestId=crypto.randomUUID();}catch(err){status(body,err.message);}finally{btn.disabled=false;}};}
 async function exportCampaign(){
  if(!current||state.busy)return toast('Aguarde a narração terminar.');let writer;
  try{const name=safeFilename(current.campaign.title).replace(/\//g,'-')+'.ndjson';if(window.showSaveFilePicker){const handle=await showSaveFilePicker({suggestedName:name,types:[{description:'Backup de campanha',accept:{'application/x-ndjson':['.ndjson']}}]});writer=await handle.createWritable();}
   const response=await authorizedFetch(base()+'/export'),reader=response.body.getReader(),decoder=new TextDecoder(),chunks=[];let size=0,tail='';
   while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;tail=(tail+decoder.decode(value,{stream:true})).slice(-4096);if(writer)await writer.write(value);else{if(size>64*1024*1024){await reader.cancel();throw Error('Backup acima de 64 MB. Use Chrome ou Edge no computador para salvar diretamente em disco.');}chunks.push(value);}}
   const last=tail.trim().split('\n').at(-1);if(JSON.parse(last).type!=='footer')throw Error('Backup interrompido: faltou a confirmação final. Tente novamente.');if(writer)await writer.close();else downloadBlob(new Blob(chunks,{type:'application/x-ndjson'}),name);toast('Backup completo salvo. Guarde uma cópia fora da hospedagem.');
  }catch(e){await writer?.abort().catch(()=>{});if(e.name!=='AbortError')toast(e.message);}
 }
 async function importCampaign(file){
  if(restoreBusy)return;restoreBusy=true;const body=modal('Restaurando sua campanha','O backup será conferido e restaurado em uma nova campanha. O original não será sobrescrito.');const feedback=status(body,'Lendo o arquivo…');let id,header,hash='0'.repeat(64),count=0,batch=[],batchBytes=0,previous,footer=null;
  const toHash=async(h,r)=>{const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(h+'\n'+JSON.stringify(r)));return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('');};
  const flush=async()=>{if(!batch.length)return;await api('/api/kelly/rpg/campaigns/'+id+'/restore-events',{method:'POST',body:JSON.stringify({events:batch,previousHash:previous})});batch=[];batchBytes=0;previous=hash;feedback.textContent=count+' registros conferidos e restaurados…';};
  try{
   const reader=file.stream().getReader(),decoder=new TextDecoder();let buffer='';
   async function record(line){if(!line.trim())return;if(footer)throw Error('Há dados inesperados após o fim do backup.');const r=JSON.parse(line);
    if(!header){if(r.type!=='header')throw Error('Cabeçalho de backup ausente.');header=r;hash=await toHash(hash,r);previous=hash;const resumeKey='kelly-restore-'+state.me.user.id+'-'+hash;id=localStorage.getItem(resumeKey)||crypto.randomUUID();let resumed;
     try{resumed=await api('/api/kelly/rpg/campaigns/'+id);}catch(e){if(e.status!==404)throw e;}
     if(resumed){if(resumed.campaign.status!=='restoring')throw Error('Este backup já foi restaurado. Abra a campanha na lista.');}
     else await api('/api/kelly/rpg/restore',{method:'POST',body:JSON.stringify({id,header:r})});localStorage.setItem(resumeKey,id);return;}
    if(r.type==='footer'){await flush();if(r.count!==count||r.hash!==hash)throw Error('O backup não passou na conferência de integridade. A campanha permanece bloqueada para revisão.');footer=r;return;}
    if(r.type!=='event'||r.seq!==count+1)throw Error('A sequência do diário está incompleta.');if(batch.length&&batchBytes+line.length>5*1024*1024)await flush();hash=await toHash(hash,r);count++;batch.push(r);batchBytes+=line.length;if(batch.length>=40||batchBytes>5*1024*1024)await flush();
   }
   try{while(true){const {value,done}=await reader.read();buffer+=done?decoder.decode():decoder.decode(value,{stream:true});let pos;while((pos=buffer.indexOf('\n'))>=0){const line=buffer.slice(0,pos);buffer=buffer.slice(pos+1);await record(line);}if(buffer.length>18*1024*1024)throw Error('Registro de backup grande demais.');if(done)break;}if(buffer.trim())await record(buffer);}finally{await reader.cancel().catch(()=>{});}
   if(!footer)throw Error('O arquivo terminou sem a confirmação de integridade. Não foi liberado para jogar.');const d=await api('/api/kelly/rpg/campaigns/'+id+'/restore-finish',{method:'POST',body:JSON.stringify({footer})});feedback.textContent='Backup restaurado: '+d.campaign.title+'.';body.append(action('Revisar e abrir a campanha','book',()=>reviewCampaign(id),'rpgPrimary'));
  }catch(e){feedback.textContent=e.message+' Você pode selecionar o mesmo arquivo para retomar uma importação interrompida.';}finally{restoreBusy=false;}
 }
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!restoreBusy)closePanel();});
 return {handles,install,destroy,clear,attach,choose,welcome,openStart,openJournal,decorate,send,exportCampaign};
})();
